<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>net8.0</TargetFramework>

    <RootNamespace>CNCSS.Data</RootNamespace>

    <AssemblyName>CNCSS.Data</AssemblyName>

  </PropertyGroup>

  <ItemGroup>

    <InternalsVisibleTo Include="CNCSS.Data.Tests" />

    <InternalsVisibleTo Include="CNCSS.Logic.Tests" />

    <InternalsVisibleTo Include="CNCSS.Tests" />

  </ItemGroup>

</Project>

